<a href="https://colab.research.google.com/github/Mustafa4564/DS_LAB/blob/main/Experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# creating matrix and computing determinant.

In [1]:


#Determinant of matrix without Numpy

print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

determinant = (
    a * (e*i - f*h)
    - b * (d*i - g*f)
    + c * (d*h - e*g)
)

print("\nDeterminant of the matrix:")
print(determinant)




Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 1 2 3
Enter row 2: 4 5 6
Enter row 3: 7 8 9

Determinant of the matrix:
0


In [2]:


#Detminant of matrix using Numpy

import numpy as np

print("Enter the elements of 3x3 matrix row-wise:")

elements = []
for i in range(3):
    row = list(map(int, input(f"Enter the row {i+1}(elements seperated by space):").split()))
    elements.append(row)

matrix = np.array(elements)

deteminant = np.linalg.det(matrix)

print("\nmatrix: ")
print(matrix)

print("determinant of the given matrix is: ")
print(deteminant)



Enter the elements of 3x3 matrix row-wise:
Enter the row 1(elements seperated by space):1 2 3
Enter the row 2(elements seperated by space):4 5 6
Enter the row 3(elements seperated by space):7 9 8

matrix: 
[[1 2 3]
 [4 5 6]
 [7 9 8]]
determinant of the given matrix is: 
8.999999999999998


In [3]:
#Inverse of the matrix without using Numpy

print("Enter the elements of the 3x3 matrix row wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

det = (
    a * (e*i - f*h)
    - b * (d*i - g*f)
    + c * (d*h - e*g)
)

print("\nDeterminant of the matrix:")
print(det)

if det == 0:
    print("Inverse of this matrix does not exist")
else:
    inverse = [

            [(e*i - f*h)/det, (c*h - b*i)/det, (b*f - c*e)/det],
            [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
            [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]

    ]

print("\nInverse of the matrix is: ")
for row in inverse:
    print(row)


Enter the elements of the 3x3 matrix row wise:
Enter row 1: 1 2 3
Enter row 2: 8 7 4
Enter row 3: 1 4 5

Determinant of the matrix:
22

Inverse of the matrix is: 
[0.8636363636363636, 0.09090909090909091, -0.5909090909090909]
[-1.6363636363636365, 0.09090909090909091, 0.9090909090909091]
[1.1363636363636365, -0.09090909090909091, -0.4090909090909091]


In [7]:


#inverse of matrix using Numpy

# Finding inverse of the matrix using function

import numpy as np

print("Enter elements of 3x3 matrix:")

A = []

for i in range(3):
    row = []
    for j in range(3):
        value = float(input(f"a[{i+1}][{j+1}]: "))
        row.append(value)
    A.append(row)

A = np.array(A)

print("\nInverse of the matrix:")
print(np.linalg.inv(A))


Enter elements of 3x3 matrix:
a[1][1]: 1
a[1][2]: 2
a[1][3]: 4
a[2][1]: 6
a[2][2]: 7
a[2][3]: 2
a[3][1]: 8
a[3][2]: 2
a[3][3]: 4

Inverse of the matrix:
[[-1.42857143e-01  6.93889390e-18  1.42857143e-01]
 [ 4.76190476e-02  1.66666667e-01 -1.30952381e-01]
 [ 2.61904762e-01 -8.33333333e-02  2.97619048e-02]]


In [8]:
#Solving system of Linear equation without using Numpy

print("Solve a system of 2 equations of the form:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

detA = a1*b2 - a2*b1

if detA == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    det_x = c1*b2 - c2*b1
    det_y = a1*c2 - a2*c1

    x = det_x / detA
    y = det_y / detA

    print("\nSolution of the system:")
    print(f"x = {round(x, 2)} , y = {round(y, 2)}")

Solve a system of 2 equations of the form:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 2
Enter b1: 4
Enter c1: 2
Enter a2: 5
Enter b2: 1
Enter c2: 2

Solution of the system:
x = 0.33 , y = 0.33


In [9]:


# Solve system of 2 linear equations using NumPy

import numpy as np

print("Solve the system:")
print("a1*x + b1*y = c1")
print("a2*x + b2*y = c2")

# Input values
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Create coefficient matrix A
A = np.array([[a1, b1],
              [a2, b2]])

# Create constant matrix B
B = np.array([c1, c2])

# Check determinant
det = np.linalg.det(A)

if det == 0:
    print("\nThe system has no unique solution (Determinant is zero).")
else:
    solution = np.linalg.solve(A, B)

    print("\nSolution of the system:")
    print("x =", solution[0])
    print("y =", solution[1])




Solve the system:
a1*x + b1*y = c1
a2*x + b2*y = c2
Enter a1: 2
Enter b1: 5
Enter c1: 6
Enter a2: 8
Enter b2: 2
Enter c2: 1

Solution of the system:
x = -0.19444444444444442
y = 1.2777777777777777
